name: PR_CI
on:
  pull_request:
    branches:
      - develop
jobs:
  run-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: YARN-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: YARN-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint

  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: YARN-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: YARN-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install
      - name: Run test
        run: yarn test --verbose

  run-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: YARN-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: YARN-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn w:build --stream
