name: Status_Build
on:
  push:
    branches:
      - main
concurrency:
  group: status-build-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  run-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: STATUS-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: STATUS-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn w:build --stream
